# .github/dependabot.yml
# Automated dependency updates for GitHub Actions and Python packages
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions - Monitor action SHAs and update to latest secure versions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    reviewers:
      - "Sevenon7"
    assignees:
      - "Sevenon7"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "security"
    # Group all actions updates together
    groups:
      github-actions:
        patterns:
          - "*"

  # Python dependencies - Monitor requirements.txt
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    reviewers:
      - "Sevenon7"
    assignees:
      - "Sevenon7"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    # Group minor/patch updates, keep major separate
    groups:
      python-minor-patch:
        update-types:
          - "minor"
          - "patch"
