name: LEAPS Daily Overlay

on:
  # 11:00 AM PT ≈ 18:00 UTC during Daylight Saving, 19:00 UTC during Standard Time.
  # We'll schedule BOTH, so it fires at 11:00 PT all year.
  schedule:
    - cron: '0 18 * * 1-5'  # PDT window (roughly Mar-Nov)
    - cron: '0 19 * * 1-5'  # PST window (roughly Nov-Mar)
  workflow_dispatch: {}      # Manual run button

permissions:
  contents: write  # needed to commit CSVs back to the repo

jobs:
  run-overlay:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas pyarrow

      - name: Run overlay script (Tradier)
        env:
          TRADIER_TOKEN: ${{ secrets.TRADIER_TOKEN }}
        run: |
          python leaps_batched_cached.py

      - name: Stamp outputs into /data/YYYY-MM-DD
        id: stamp
        run: |
          DATE_DIR="data/$(date -u +%Y-%m-%d)"
          mkdir -p "$DATE_DIR"
          # Move outputs produced by the script (adjust names if you changed them)
          mv overlay_vwap_macd_rsi.csv "$DATE_DIR/overlay_vwap_macd_rsi.csv"
          mv option_pl.csv               "$DATE_DIR/option_pl.csv"
          mv gapdown_above_100sma.csv    "$DATE_DIR/gapdown_above_100sma.csv"
          # Create a quick human summary
          echo "# LEAPS Overlay ($(date -u))" > "$DATE_DIR/SUMMARY.md"
          echo "" >> "$DATE_DIR/SUMMARY.md"
          echo "Artifacts:" >> "$DATE_DIR/SUMMARY.md"
          echo "- overlay_vwap_macd_rsi.csv" >> "$DATE_DIR/SUMMARY.md"
          echo "- option_pl.csv" >> "$DATE_DIR/SUMMARY.md"
          echo "- gapdown_above_100sma.csv" >> "$DATE_DIR/SUMMARY.md"
          echo "date_dir=$DATE_DIR" >> $GITHUB_OUTPUT

      - name: Compute raw URLs
        id: raw
        run: |
          DATE_DIR="data/$(date -u +%Y-%m-%d)"
          REPO="${{ github.repository }}"
          echo "raw1=https://raw.githubusercontent.com/${REPO}/main/${DATE_DIR}/overlay_vwap_macd_rsi.csv" >> $GITHUB_OUTPUT
          echo "raw2=https://raw.githubusercontent.com/${REPO}/main/${DATE_DIR}/option_pl.csv" >> $GITHUB_OUTPUT
          echo "raw3=https://raw.githubusercontent.com/${REPO}/main/${DATE_DIR}/gapdown_above_100sma.csv" >> $GITHUB_OUTPUT

      - name: Append raw links to summary
        run: |
          {
            echo "### Raw CSV links (UTC $(date -u))"
            echo "- ${{ steps.raw.outputs.raw1 }}"
            echo "- ${{ steps.raw.outputs.raw2 }}"
            echo "- ${{ steps.raw.outputs.raw3 }}"
          } >> $GITHUB_STEP_SUMMARY

      - name: Commit results
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add ${{ steps.stamp.outputs.date_dir }}
          git commit -m "LEAPS overlay auto-run: ${{ steps.stamp.outputs.date_dir }}"
          git push

      - name: Upload artifacts (optional but handy)
        uses: actions/upload-artifact@v4
        with:
          name: leaps-report
          path: |
            ${{ steps.stamp.outputs.date_dir }}/overlay_vwap_macd_rsi.csv
            ${{ steps.stamp.outputs.date_dir }}/option_pl.csv
            ${{ steps.stamp.outputs.date_dir }}/gapdown_above_100sma.csv
            ${{ steps.stamp.outputs.date_dir }}/SUMMARY.md
