name: LEAPS Consumer (read latest.json + emit digest + VWAP heads-up)

on:
  schedule:
    - cron: '0 18 * * 1-5'  # ~11:00 AM PT during PDT
    - cron: '0 19 * * 1-5'  # ~11:00 AM PT during PST
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  consume:
    runs-on: ubuntu-latest
    env:
      DESIRED_PT_TIME: "11:00"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Time Gate (America/Los_Angeles)
        id: timegate
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          NOW_PT=$(TZ=America/Los_Angeles date +%H:%M)
          TARGET="${DESIRED_PT_TIME}"
          echo "Now PT: $NOW_PT | Target PT: $TARGET"
          if [ "$NOW_PT" >= "$TARGET" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"
          else
            echo "should_run=false" >> "$GITHUB_OUTPUT"
            echo "Not target PT time -> fast exit."
          fi

      - name: Ensure requirements.txt
        if: steps.timegate.outputs.should_run == 'true'
        run: |
          if [ ! -f requirements.txt ] ; then
            printf "requests>=2.31,<3\npandas>=2.2,<3\n" > requirements.txt
          fi

      - name: Setup Python
        if: steps.timegate.outputs.should_run == 'true'
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install deps
        if: steps.timegate.outputs.should_run == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run consumer (build digest + VWAP report)
        if: steps.timegate.outputs.should_run == 'true'
        env:
          REPO: Sevenon7/Tradier_Options
          MAX_AGE_HOURS: "24"
          RETRY_COUNT: "3"
          RETRY_SLEEP: "1.2"
        run: |
          python consumer_latest_reader.py
          {
            echo "### Consumer Output ($(date -u))"
            echo
            echo '```json'
            cat analysis_digest.json
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - name: VWAP Missing Heads-up (warnings + summary)
        if: steps.timegate.outputs.should_run == 'true'
        shell: bash
        run: |
          if [ -f vwap_missing.json ]; then
            COUNT=$(python -c 'import json;print(json.load(open("vwap_missing.json")).get("count",0))')
            echo "VWAP-missing count: $COUNT"
            echo "### VWAP Missing Report" >> "$GITHUB_STEP_SUMMARY"
            if [ -f vwap_missing.md ]; then
              cat vwap_missing.md >> "$GITHUB_STEP_SUMMARY"
            fi
            if [ "$COUNT" -gt 0 ]; then
              python tools/vwap_warn.py
            fi
          else
            echo "No vwap_missing.json present."
          fi

      - name: Commit digest files
        if: steps.timegate.outputs.should_run == 'true'
        run: |
          set -eo pipefail
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add analysis_digest.json analysis_digest.md vwap_missing.json vwap_missing.md
          git commit -m "Consumer digest + VWAP report $(date -u +%Y-%m-%dT%H:%M:%SZ)" || true
          git push
