name: LEAPS Daily Overlay

on:
  # 11:00 AM PT ≈ 18:00 UTC during DST and 19:00 UTC during Standard Time.
  # Use BOTH to cover the year; we’ll guard duplicates below.
  schedule:
    - cron: '0 18 * * 1-5'  # PDT (roughly Mar–Nov)
    - cron: '0 19 * * 1-5'  # PST (roughly Nov–Mar)
  workflow_dispatch: {}      # Manual run button in Actions tab

permissions:
  contents: write  # allow committing outputs back to the repo

jobs:
  run-overlay:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas pyarrow

      - name: Skip if already ran today (avoid double-run on DST crons)
        id: skipcheck
        run: |
          DATE_DIR="data/$(date -u +%Y-%m-%d)"
          if [ -d "$DATE_DIR" ]; then
            echo "already=true" >> $GITHUB_OUTPUT
          else
            echo "already=false" >> $GITHUB_OUTPUT

      - name: Run overlay script (Tradier)
        if: steps.skipcheck.outputs.already == 'false'
        env:
          TRADIER_TOKEN: ${{ secrets.TRADIER_TOKEN }}
        run: |
          python leaps_batched_cached.py

      - name: Prepare dated folder
        if: steps.skipcheck.outputs.already == 'false'
        id: stamp
        run: |
          DATE_DIR="data/$(date -u +%Y-%m-%d)"
          mkdir -p "$DATE_DIR"
          mv overlay_vwap_macd_rsi.csv "$DATE_DIR/overlay_vwap_macd_rsi.csv"
          mv option_pl.csv               "$DATE_DIR/option_pl.csv"
          mv gapdown_above_100sma.csv    "$DATE_DIR/gapdown_above_100sma.csv"
          printf "# LEAPS Overlay (%s UTC)\n\nArtifacts:\n- overlay_vwap_macd_rsi.csv\n- option_pl.csv\n- gapdown_above_100sma.csv\n" "$(date -u)" > "$DATE_DIR/SUMMARY.md"
          echo "date_dir=$DATE_DIR" >> $GITHUB_OUTPUT

      - name: Commit results
        if: steps.skipcheck.outputs.already == 'false'
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add ${{ steps.stamp.outputs.date_dir }}
          git commit -m "LEAPS overlay auto-run: ${{ steps.stamp.outputs.date_dir }}"
          git push

      - name: Upload artifacts
        if: steps.skipcheck.outputs.already == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: leaps-report
          path: |
            ${{ steps.stamp.outputs.date_dir }}/overlay_vwap_macd_rsi.csv
            ${{ steps.stamp.outputs.date_dir }}/option_pl.csv
            ${{ steps.stamp.outputs.date_dir }}/gapdown_above_100sma.csv
            ${{ steps.stamp.outputs.date_dir }}/SUMMARY.md
